apiVersion: groups.gitlab.crossplane.io/v1alpha1
kind: Group
metadata:
  name: example-group
  annotations:
    #crossplane.io/external-name: Example Group
spec:
  managementPolicies: ["Observe"]
  forProvider:
    # If not set, metadata.name will be used instead.
    name: "Example Group"
    path: "example-group-path"
    description: "example group description"
    parentId: 117234999
  providerConfigRef:
    name: gitlab-provider
  # a reference to a Kubernetes secret to which the controller will write the runnersToken
  writeConnectionSecretToRef:
    name: gitlab-group-example-group
    namespace: crossplane-system
